name: Dev - Deploy

env:
  ENVIRONMENT: "dev"

on:
  pull_request:
    branches:
      - ${{ env.ENVIRONMENT }}
    types: [closed]

jobs:
  context:
    runs-on: ubuntu-latest
    outputs:
      should-publish: ${{ steps.context.outputs.should-publish }}
      release-type: ${{ steps.context.outputs.release-type }}
      next-version: ${{ steps.increment-version.outputs.next-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Establish context
        id: context
        uses: dolittle/establish-context-action@v2
        with:
          environment-branch: ${{ env.ENVIRONMENT }}

      - name: Increment version
        id: increment-version
        if: ${{ steps.context.outputs.should-publish == 'true' }}
        uses: dolittle/increment-version-action@v2
        with:
          version: ${{ steps.context.outputs.current-version }}
          release-type: ${{ steps.context.outputs.release-type }}

  deploy:
    if: ${{ needs.context.outputs.should-publish == 'true' }}
    needs: context
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create GitHub Release
        uses: dolittle/github-release-action@v2
        if: ${{ needs.context.outputs.should-publish == 'true' }}
        with:
          version: ${{ needs.context.outputs.next-version }}
          body: ${{ needs.context.outputs.pr-body }}
      ## Do deployment here
